[window]
padding = {x=5, y=5}
#opacity = 0.8

[font]
normal = {family="Fira Code", style="Regular"}
bold = {family="Fira Code", style="Bold"}
italic = {family="Fira Code", style="Italic"}
bold_italic = {family="Fira Code", style="Bold Italic"}
size = 7.5

[colors]
[colors.primary]
foreground = "#cbccc6"
background= "#1f1f23"
[colors.normal]
black = "#090618"
red = "#ff3333"
green = "#c2d94c"
yellow = "#ff8f40"
blue = "#0b7ed2"
magenta = "#c678dd"
cyan = "#5fdaff"
white = "#cbccc6"
[colors.bright]
black = "#727169"
red = "#ff0000"
green = "#aec82a"
yellow = "#ff710d"
blue = "#1d99f3"
magenta = "#b54fd3"
cyan = "#2cceff"
white = "#e2e3dc"
